<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title><?php echo SITE_NAME; ?></title>
    <meta name="description" content="">
    <meta name="author" content="">

    <meta name="viewport" content="width=960">
    <meta property="og:image" content="<?php echo HTTP_ROOT; ?>/images/fbfb.png"/>

    <?php echo $this->minifyHeadLink()
        ->prependStylesheet('/css/game.css')
        ->prependStylesheet('/css/formation.css')
        ->prependStylesheet('/css/roster.css')
        ->prependStylesheet('/css/ranking.css')
        ->prependStylesheet('/css/skillgame.css')
        ->prependStylesheet('/css/match.css')
        ->prependStylesheet('/css/typeahead.css')
        ->prependStylesheet('/css/bootstrap.min.css'); ?>

    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Squada+One|Roboto:400,300,900' rel='stylesheet' type='text/css'>

    <script src="/js/libs/jquery-1.10.2.min.js"></script>
    <script src="/js/libs/jquery-ui-1.9.1.custom.min.js"></script>

    <script src="/js/libs/modernizr-2.5.3.min.js"></script>
    <script src="/js/libs/typeahead.min.js"></script>
    <script src="/js/libs/bootstrap/button.js"></script>
    <script src="/js/libs/bootstrap/dropdown.js"></script>
    <script src="/js/libs/bootstrap/modal.js"></script>
    <script src="/js/libs/bootstrap/tooltip.js"></script>
    <script src="/js/libs/bootstrap/popover.js"></script>

    <script src="/js/libs/jquery.path.js"></script>

    <script src="//connect.facebook.net/en_US/all.js"></script>
</head>
<body>
<?php //echo $this->facebook(FB_APP_ID)->initialize(); ?>

<div>
    <div class="main">
        <?php /* TODO: Escape HTML Chars in breadcrumb */ //echo $this->navigation()->breadcrumbs()->render();?>
        <?php if($this->title){ ?>
            <div class="page-header">
                <h1><?php echo $this->title ?>
                    <?php if($this->headline){ ?>
                        <small><?php echo $this->headline; ?></small>
                    <?php } ?>
                </h1>
            </div>
        <?php } ?>
        <?php echo $this->layout()->content ?>
    </div>
</div>

<div class="modal fade" id="eventModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

    <script src="/js/plugins.js"></script>
    <script src="/js/script.js"></script>
</body>
</html>