<?php if(count($this->players)<11){ ?>
    <div class="alert alert-warning lessthan11">
        Du hast derzeit weniger als 11 Spieler aufgestellt! Nicht gut! Könnte in einem Match evtl. einen entscheidenden Nachteil darstellen. Stelle sicher dass du möglichst viele Spieler aufgestellt hast!
    </div>
<?php }
list($defense,$midfield,$offense) = explode('-',$this->formation);
$pos = 11;
?>
<div class="pitch" id="pitch">
    <div class="formation">
        <div class="offense line">
            <?php for($i=0;$i<$offense;$i++){
                echo $this->partial('_player.phtml',array('position'=>$pos,'player'=>$this->players[$pos]));
                $pos--;
            } ?>
        </div>
        <div class="midfield line">
            <?php for($i=0;$i<$midfield;$i++){
                echo $this->partial('_player.phtml',array('position'=>$pos,'player'=>$this->players[$pos]));
                $pos--;
            } ?>
        </div>
        <div class="defense line">
            <?php for($i=0;$i<$defense;$i++){
                echo $this->partial('_player.phtml',array('position'=>$pos,'player'=>$this->players[$pos]));
                $pos--;
            } ?>
        </div>
        <div class="goalkeeper line">
            <?php echo $this->partial('_player.phtml',array('position'=>1,'player'=>$this->players['1'])); ?>
        </div>
    </div>
</div>
