<h2>Challenge Your Friends</h2>
<?php if($this->friends){ ?>
<p>Hier kannst du Freundschaftsspiele gegen deine Freunde austragen.</p>
<div class="row">
    <div class="col-lg-6" id="ranking">
        <?php foreach($this->friends as $f){ ?>
            <div class="team clearfix" data-id="<?php echo $f['id']; ?>">
                <div class="name"><?php echo $f['name']; ?></div>
                <div class="picture"><img class="thumbnail" src="http://graph.facebook.com/<?php echo $f['fb_uid']; ?>/picture"></div>
                <div class="description"><?php echo $f['fb_name']; ?></div>
                <a class="btn btn-default" href="<?php echo $this->url(array('controller'=>'match','action'=>'start','away_team_id'=>$f['id'])); ?>">
                    <i class="fa fa-circle-arrow-right"></i> Challenge <?php echo $f['fb_name']; ?>
                </a>
            </div>
        <?php } ?>
    </div>
</div>
<?php } ?>
<h4>Warum nicht jemanden einladen?</h4>
<p><a href="#" class="inviteBtn btn btn-default">Invite your friends!</a></p>
<script>
    $('.inviteBtn').click(function(){
        FB.ui({
            method: 'feed',
            link: '<?php echo HTTP_ROOT ?>/game',
            caption: 'Ein lustiges Facebook Fussball-Game, deine Mannschaft sind deine Freunde. Voll beta. Jetzt testen. Danke!'
        }, function(response){});
    })
</script>
<p>Folgende Spiele sind noch offen:</p>
<?php foreach($this->open as $m){ ?>
    <div class="team clearfix" data-id="<?php echo $m['id']; ?>">
        <div class="name"><?php echo $m['name']; ?></div>
        <div class="picture"><img class="thumbnail" src="http://graph.facebook.com/<?php echo $m['fb_uid']; ?>/picture"></div>
        <div class="description"><?php echo $m['fb_name']; ?></div>
        <a class="btn btn-default" href="<?php echo $this->url(array('controller'=>'match','action'=>'view','match_id'=>$m['match_id'])); ?>">
            <i class="fa fa-circle-arrow-right"></i> Resume this match!
        </a>
    </div>
<?php } ?>