<form action="<?php echo $this->url(); ?>" method="post">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Select Formation</h4>
            </div>
            <div class="modal-body">
                <?php foreach($this->formations as $f){ ?>
                    <div class="col-md-4">
                        <input type="radio" name="formation_id" value="<?php echo $f['id']; ?>" /> <?php echo $f['name']; ?>
                    </div>
                <?php } ?>
            </div>
            <div class="modal-footer">
                <input type="submit" class="btn btn-default" value="OK">
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
