<div>
    <h1>Willkommen bei <?php echo SITE_NAME; ?></h1>
    <p><?php echo SITE_NAME; ?> ist ein soziales Fussballspiel. Es hat Elemente von klassischen Fussball-Manager Games sowie die soziale Komponente wie man sie von FarmVille kennt. Das Spiel ist gratis und in einer sehr frühen Testphase.</p>
    <p><a class="btn btn-primary btn-large" href="<?php echo $this->loginUrl; ?>">Jetzt spielen!</a></p>
</div>

<?php if($this->loginUrl){ ?>
    <p>
        <fb:login-button show-faces="true" width="200" max-rows="1"></fb:login-button>
    </p>
<?php }else{ ?>
    <p>
        <a href="<?php echo $this->logoutUrl; ?>">Logout</a>
    </p>
<?php } ?>
