<h2>Challenge Your Friends</h2>
<?php if($this->friends){ ?>
<p>Hier kannst du Freundschaftsspiele gegen deine Freunde austragen.</p>
<div class="row">
    <div class="col-lg-6" id="ranking">
        <?php foreach($this->friends as $f){ ?>
            <div class="team clearfix" data-id="<?php echo $f['id']; ?>">
                <div class="name"><?php echo $f['name']; ?></div>
                <div class="picture"><img src="<?php echo $f['profile_pic']; ?>"></div>
                <div class="description"><?php echo $f['fb_name']; ?></div>
                <a class="btn btn-default" href="<?php echo $this->url(array('controller'=>'match','action'=>'index','away_team_id'=>$f['id'])); ?>">
                    <i class="icon-circle-arrow-right"></i> Challenge <?php echo $f['fb_name']; ?>
                </a>
            </div>
        <?php } ?>
    </div>
</div>
<?php }else{ ?>
    <p>Es scheint als spielen deine Freunde noch nicht <?php echo SITE_NAME; ?>!</p>
<?php } ?>
<h4>Warum nicht jemanden einladen?</h4>
<p><a href="#" class="inviteBtn btn btn-default">Invite your friends!</a></p>
<script>
    $('.inviteBtn').click(function(){
        FB.ui({
            method: 'feed',
            link: '<?php echo HTTP_ROOT ?>/game',
            caption: 'Ein lustiges Facebook Fussball-Game - spiele mit deinen Freunden. Voll beta.'
        }, function(response){});
    })
</script>