<?php
$s = $this->situation;
if(!$s['running']){ ?>
    <a class="btn btn-primary actionButton" data-loading-text="attempting..." data-instruction="start">
        Kick off!
    </a>
<?php }elseif($s['type'] == 'offense'){ ?>
    <?php if($s['running'] && $s['player']->getPosition()!=1){ ?>
        <a class="btn btn-primary actionButton" data-loading-text="attempting..." data-instruction="dribble">
            Dribble on!
        </a>
    <?php } ?>
    <a class="btn btn-primary actionButton" data-loading-text="attempting..." data-instruction="pass">
        Pass the ball!
    </a>
    <?php if($s['shoot']){ ?>
        <a data-toggle="modal" data-target="#modalForm" data-remote="<?php echo $this->url(array('action'=>'skillgame')); ?>" class="btn btn-primary actionButton" data-loading-text="attempting..." data-instruction="shoot">
            SHOOT!
        </a>
    <?php } ?>
    <?php if($s['clear']){ ?>
        <a class="btn btn-primary actionButton" data-loading-text="attempting..." data-instruction="clear">
            clear Ball!
        </a>
    <?php } ?>
<?php }elseif($s['type'] == 'defense'){ ?>
    <a class="btn btn-primary actionButton" data-loading-text="attempting..." data-instruction="start">
        Go on...
    </a>
<?php }else{ ?>
    <a class="btn btn-primary actionButton" data-loading-text="attempting..." data-instruction="start">
        Play on!
    </a>
<?php } ?>
