<?php $pitch = $this->pitch; ?>
<div class="ball" style="top: <?php echo $pitch['ball']['y']; ?>%; left: <?php echo $pitch['ball']['x']; ?>%"></div>
<div class="player" style="top: <?php echo $pitch['ball']['y']; ?>%; left: <?php echo $pitch['ball']['x']+($pitch['side']==1?-10:10); ?>%">
    <?php if($this->pitch['player']){ ?>
        <img src="<?php echo $this->pitch['player']['profile_pic']; ?>" class="thumbnail">
    <?php } ?>
</div>
