<div class="row">
    <div class="col-lg-12 score">
        <?php echo $this->summary['standing']; ?>
    </div>
</div>
<div class="summary">
    <?php foreach($this->summary['goals'] as $event){ ?>
        <div class="row">
            <div class="col-lg-6<?php if($event['side']==1){ echo " col-lg-offset-6"; } ?>">
                <span class="label label-info"><?php echo $event['minute']; ?></span>
                <?php echo $event['player_name']; ?>
            </div>
        </div>
    <?php } ?>
</div>