<div class="row" id="match">
    <div class="col-lg-8">
        <a class="pull-right btn btn-danger btn-small" id="actionButton" href="<?php echo $this->url(array('reset'=>1)); ?>">
            <i class="icon-refresh"></i> Reset Match
        </a>
        <div class="controls" id="matchControls">
            <?php echo $this->partial('match/_controls.phtml',array('situation'=>$this->situation)); ?>
        </div>
        <div id="skillContainer">

        </div>
        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title">Match Log</h3></div>
            <div id="matchLog" class="panel-body">
                <?php echo $this->partial('match/_log.phtml',array('log'=>$this->log)); ?>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="panel panel-success">
            <div class="panel-heading"><h3 class="panel-title">Pitch Situation</h3></div>
            <div id="pitch" class="panel-body">
                <?php $pitch = $this->pitch; ?>
                <div class="pitch">
                    <?php echo $this->partial('match/_pitch.phtml',array('pitch'=>$this->pitch)); ?>
                </div>
            </div>
        </div>
        <div class="panel panel-primary">
            <div class="panel-heading"><h3 class="panel-title">Match Summary</h3></div>
            <div class="row panel-body">
                <div class="col-lg-6">
                    <h4 style="text-align: right;"><span class="label label-success"><?php echo $this->homeTeam->getName(); ?></span></h4>
                </div>
                <div class="col-lg-6">
                    <h4><span class="label label-danger"><?php echo $this->awayTeam->getName(); ?></span></h4>
                </div>
                <div id="summary">
                    <?php echo $this->partial('match/_summary.phtml',array('summary'=>$this->summary)); ?>
                </div>
            </div>
        </div>

    </div>
</div>

<div class="modal fade" id="skillgameModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

</div><!-- /.modal -->

<script>
$(document).ready(function () {
    $('.skillContainer').hide();
    initControls();
});

function initControls(){
    $('#matchControls .actionButton').click(function(){
        var button = $(this);
        var instruction = button.data('instruction');
        var skill = button.data('skill');
        //button.button('loading');
        $('#matchControls .actionButton').hide();

        if (instruction=='shoot'){
            // Hook Shooting Skillgame
            initSkillModifier(instruction, skill, function(instruction,skill){
                $('#skillgameModal').modal({
                    remote: "<?php echo $this->url(array('action'=>'skillgame')); ?>/skill/"+skill
                });
            });
        }
        else if (button.hasClass('skillModified')) {
            initSkillModifier(instruction, skill, loadGameAction);
        } else {
            loadGameAction(instruction);
        }

    });
}

function animateGauge(container,skill){
    var width = parseInt(container.css('width'));
    var parentWidth = parseInt(container.parent().css('width'));
    if(skill=='power'){
        if (width < 10) {
            container.css('width', '100%');
        } else {
            container.css('width', '0%');
        }
    }else if(skill=='accuracy'){
        if (width < 10) {
            container.css('width', '100%');
        } else {
            container.css('width', '0%');
        }
    }
}
function initSkillModifier(instruction, skill, callback) {

    var progress = document.createElement('div');
    $(progress).addClass('progress '+skill);

    var progressBar = document.createElement('div');
    $(progressBar).addClass('progress-bar gauge');
    $(progressBar).css('width','50%');

    var hitButton = document.createElement('a');
    $(hitButton).addClass('btn hit btn-primary');
    $(hitButton).html('Hit it!');

    $(progressBar).appendTo($(progress));
    $(progress).appendTo($('#skillContainer'));
    $(hitButton).appendTo($('#skillContainer'));

    animateGauge($(progressBar),skill);
    var gaugeInterval = setInterval(function () {
        animateGauge($(progressBar),skill);
    }, parseFloat($(progressBar).css('transition-duration')) * 1100);

    $(hitButton).click(function(){
        clearInterval(gaugeInterval);
        $(progressBar).css('width',$(progressBar).css('width'));
        callback(instruction, skill);
    })
};

function loadEvent(data,i) {
    if (data.html[++i]) {
        $('#matchLog .log').prepend(data.html[i]);
        $('#matchLog .log .row:first').slideDown(500, function () {

            $('.pitch .ball').animate({
                'left': data.log[i].ball.x + '%',
                'top': data.log[i].ball.y + '%'
            }, 500, "linear");

            if (data.log[i].player_pic) {
                $('#pitch .player').html('');
                if (data.log[i].side == 1) {
                    $('#pitch .player').css('left', (data.log[i].ball.x - 2) + '%');
                    $('#pitch .player').css('top', data.log[i].ball.y + 1 + '%');
                } else if (data.log[i].side == 2) {
                    $('#pitch .player').css('left', (data.log[i].ball.x + 2) + '%');
                    $('#pitch .player').css('top', data.log[i].ball.y + 1 + '%');
                }
                var img = $('<img />'); //Equivalent: $(document.createElement('img'))
                img.attr('class', 'thumbnail');
                img.attr('src', data.log[i].player_pic);
                $('#pitch .player').html(img);
            }

            console.log('Recursively looking for next!');
            setTimeout(function(){
                loadEvent(data,i);
            }, 1500);
        });
    } else {
        $('#matchControls').html(data.controls);
        initControls();
    }
}

function loadGameAction(instruction, skill, callback) {

    var skillModifier = 0;
    if(typeof skill !== 'undefined'){
        var pct = (parseInt($('#skillContainer').find('.gauge').css('width')) / parseInt($('#skillContainer').find('.gauge').parent().css('width')))*100;
        if(skill=='power'){
            skillModifier = pct;
        }else{
            skillModifier = (50-Math.abs(50-pct))*2;
            console.log(skillModifier);
        }
        $('#skillContainer').html('');
    }

    $.ajax({
        url: "<?php echo $this->url(array('action'=>'play')); ?>",
        data: {
            'instruction': instruction,
            'skill': skillModifier
        }
    }).done(function (jsonData) {
        data = $.parseJSON(jsonData);

        if(typeof callback !== 'undefined'){
            for(var j=0;j<data.log.length;j++){
                if(data.log[j].action!=null){
                    callback(data.log[j].action);
                }
            }
            setTimeout(function () {
                $('#skillgameModal').modal('hide');
                $('#skillgameModal').removeData('bs.modal')
                loadEvent(data,-1);
            }, 1500);
        }else{
            loadEvent(data,-1);
        }

        $('#summary').html(data.summary);
    });
}
</script>
