<div class="row" id="match">
    <div class="col-lg-8">
        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title">Match Log</h3></div>
            <div id="matchLog" class="panel-body">
                <?php echo $this->partial('match/_log.phtml',array('log'=>$this->log)); ?>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <a class="pull-right btn btn-danger btn-small" id="actionButton" href="<?php echo $this->url(array('reset'=>1)); ?>">
                    <i class="icon-refresh"></i> Reset Match
                </a>
                <h3 class="panel-title">Controls</h3>
            </div>
            <div class="panel-body controls" id="matchControls">
                <?php echo $this->partial('match/_controls.phtml',array('situation'=>$this->situation)); ?>
            </div>
        </div>
        <div class="panel panel-primary">
            <div class="panel-heading"><h3 class="panel-title">Match Summary</h3></div>
            <div class="row panel-body">
                <div class="col-lg-6">
                    <h4 style="text-align: right;"><span class="label label-success"><?php echo $this->homeTeam->getName(); ?></span></h4>
                </div>
                <div class="col-lg-6">
                    <h4><span class="label label-danger"><?php echo $this->awayTeam->getName(); ?></span></h4>
                </div>
                <div id="summary">
                    <?php echo $this->partial('match/_summary.phtml',array('summary'=>$this->summary)); ?>
                </div>
            </div>
        </div>
        <div class="panel panel-success">
            <div class="panel-heading"><h3 class="panel-title">Pitch Situation</h3></div>
            <div id="pitch" class="panel-body">
                <?php $pitch = $this->pitch; ?>
                <div class="pitch">
                    <?php echo $this->partial('match/_pitch.phtml',array('pitch'=>$this->pitch)); ?>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="skillgameModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

</div><!-- /.modal -->

<script>
    $(document).on('click','.actionButton',function(){

        var button = $(this);
        var instruction = button.data('instruction');
        button.button('loading');

        if(instruction==='shoot'){
            $('#skillgameModal').modal({
                remote: "<?php echo $this->url(array('action'=>'skillgame')); ?>"
            })
        }else{
            loadGameAction(instruction)
        }


    });

    function loadGameAction(instruction){
        $.ajax({
            url: "<?php echo $this->url(array('action'=>'play')); ?>",
            data: {'instruction': instruction}
        }).done(function ( jsonData ) {
            data = $.parseJSON(jsonData);

            var i = -1;

            loadEvent = function(){
                if(data.html[++i]){
                    $('#matchLog .log').prepend(data.html[i]);
                    $('#matchLog .log .row:first').slideDown( 100,function(){

                        $('.pitch .ball').animate({ 'left':data.log[i].ball.x+'%', 'top':data.log[i].ball.y+'%' }, 200, "linear");

                        if(data.log[i].player_pic){
                            var img = $('<img />'); //Equivalent: $(document.createElement('img'))
                            img.attr('class', 'thumbnail');
                            img.attr('src', data.log[i].player_pic);
                            $('#pitch .player').html(img);
                            if(data.log[i].side==1){
                                $('#pitch .player').animate({ 'left':(data.log[i].ball.x-10)+'%', 'top':data.log[i].ball.y+'%' },200);
                            }else if(data.log[i].side==2){
                                $('#pitch .player').animate({ 'left':(data.log[i].ball.x+10)+'%', 'top':data.log[i].ball.y+'%' },200);
                            }
                        }

                        setTimeout(loadEvent,700);
                    });
                }else{
                    $('#matchControls').html(data.controls);
                }
            }
            loadEvent();

            setTimeout(function () {
                $('#skillgameModal').modal('hide');
                $('#skillgameModal').removeData('bs.modal')
            },1000);

            $('#summary').html(data.summary);
        });
    }

</script>
