<?php foreach($this->matches as $m){ ?>
    <div class="team clearfix" data-id="<?php echo $m['id']; ?>">
        <div class="name"><?php echo $m['name']; ?></div>
        <div class="picture"><img class="thumbnail" src="http://graph.facebook.com/<?php echo $m['fb_uid']; ?>/picture"></div>
        <div class="description"><?php echo $m['fb_name']; ?></div>
        <a class="btn btn-default" href="<?php echo $this->url(array('controller'=>'match','action'=>'view','match_id'=>$m['match_id'])); ?>">
            <i class="fa fa-circle-arrow-right"></i> Resume this match!
        </a>
    </div>
<?php } ?>