<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <!--            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>-->
            <h4 class="modal-title">Your chance to score!</h4>
        </div>
        <div class="modal-body">
            <div id="skillgame">
                <div class="background">
                    <div class="goal" id="goal">
                        <div class="target" data-coord="1"></div>
                        <div class="target" data-coord="2"></div>
                        <div class="target" data-coord="3"></div>
                        <div class="target keeper" data-coord="4"></div>
                        <div class="target keeper" data-coord="5"></div>
                        <div class="target keeper" data-coord="6"></div>
                        <div id="keeper" style="position: absolute; top: 75px; left: 50%; margin-left: -30px;"><img src="<?php echo $this->keeper->getPicture(); ?>"></div>
                    </div>
                    <div id="ball" class="ball" style="left:<?php echo $this->ball['x']; ?>; top: <?php echo $this->ball['y']; ?>">
                        <img src="/css/images/ball.png" width="80" height="80" />
                    </div>
                    <div id="player" class="player" style="left:<?php echo $this->ball['x']-2; ?>%; top: <?php echo $this->ball['y']-2; ?>%;">
                        <img src="<?php echo $this->player->getPicture(); ?>" />
                    </div>
                </div>
            </div>
        </div>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->

<script>
    $('.target').click(function(){

        var target = $(this);
        loadGameAction('shoot',true,function(action){
            shootBall(target,action);
        })

    });

    function shootBall(target,action){
        var ball = $('#ball');
        var goal = $('#goal');

        if(action!='miss'){
            var bezier_params = {
                start: {
                    x: parseInt(ball.css('left')),
                    y: parseInt(ball.css('top')),
                    angle: 45
                },
                end: {
                    x: parseInt(target.get(0).offsetLeft+goal.get(0).offsetLeft+Math.floor(parseInt(target.css('width'))/2)-30),
                    y: parseInt(target.get(0).offsetTop+goal.get(0).offsetTop+Math.floor(parseInt(target.css('height'))/2)-30),
                    angle: -45,
                    length: 0.25
                }
            }
        }else{
            var bezier_params = {
                start: {
                    x: parseInt(ball.css('left')),
                    y: parseInt(ball.css('top')),
                    angle: 45
                },
                end: {
                    x: parseInt(Math.random()*parseInt($('#goal').css('width'))),
                    y: 30,
                    angle: -45,
                    length: 0.25
                }
            }
        }
        ball.animate({path : new $.path.bezier(bezier_params),rotation: 360},1000);
        ball.find('img').animate({width: "-=40", height: "-=40"},1000);

        setTimeout(function(){keeperSave(target.data('coord'),action)},500);
    }

    function keeperSave(coord,action){

        var keeper = $('#keeper');
        if(action=='save'){
            var target = $('#goal').find("[data-coord='" + coord + "']");
        }
        else if(action=='score'){
            var targetCoord=coord;
            while(coord==targetCoord){
                var targetCoord = 1 + Math.floor(Math.random() * 6);
            }
            var target = $('#goal').find("[data-coord='" + targetCoord + "']");
        }
        if(typeof target !== 'undefined'){
            var leftTarget = target.get(0).offsetLeft+Math.floor(parseInt(target.css('width'))/2);
            var topTarget = target.get(0).offsetTop+Math.floor(parseInt(target.css('height'))/2)-30;
            keeper.animate({left:leftTarget,top:topTarget},500);
        }

    }
</script>