<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Something's happening!</h4>
        </div>
        <div class="modal-body">
            <?php echo $this->partial('_event.phtml',array('event'=>$this->event)); ?>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">OK</button>
        </div>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->
<script>
    $(document).ready(function(){

        $('.progress-bar').each(function() {
            var me = $(this);
            var perc = me.data("percentage")/100;
            var maxWidth = parseInt(me.parent().css('width'));

            me.animate({'width': parseInt(maxWidth*perc)+'px'},1000)

        });

    });
</script>